#ifndef _config_h_
#define _config_h_
#include <SDL2/SDL.h>

// app parameters
#define DEBUG 0
#define FULLSCREEN 0
#define WINDOW_WIDTH 240
#define WINDOW_HEIGHT 320
#define VSYNC 1
#define SCROLL_THRESHOLD 0.1
#define MAX_MESSAGES 4
#define DB_PATH "craft.db"
#define USE_CACHE 1
#define DAY_LENGTH 600
#define INVERT_MOUSE 0

// rendering options
#define SHOW_LIGHTS 1
#define SHOW_PLANTS 1
#define SHOW_CLOUDS 1
#define SHOW_TREES 1
#define SHOW_ITEM 1
#define SHOW_CROSSHAIRS 1
#define SHOW_WIREFRAME 1
#define SHOW_INFO_TEXT 1
#define SHOW_CHAT_TEXT 1
#define SHOW_PLAYER_NAMES 1

// key bindings
#define CRAFT_KEY_FORWARD SDL_SCANCODE_W
#define CRAFT_KEY_BACKWARD SDL_SCANCODE_S
#define CRAFT_KEY_LEFT SDL_SCANCODE_A
#define CRAFT_KEY_RIGHT SDL_SCANCODE_D
#define CRAFT_KEY_JUMP SDL_SCANCODE_SPACE
#define CRAFT_KEY_FLY SDL_SCANCODE_TAB
#define CRAFT_KEY_OBSERVE SDL_SCANCODE_O
#define CRAFT_KEY_OBSERVE_INSET SDL_SCANCODE_P
#define CRAFT_KEY_ITEM_NEXT SDL_SCANCODE_E
#define CRAFT_KEY_ITEM_PREV SDL_SCANCODE_R
#define CRAFT_KEY_ZOOM SDL_SCANCODE_LSHIFT
#define CRAFT_KEY_ORTHO SDL_SCANCODE_F
#define CRAFT_KEY_CHAT SDL_SCANCODE_T
#define CRAFT_KEY_COMMAND SDL_SCANCODE_SLASH
#define CRAFT_KEY_SIGN SDL_SCANCODE_DELETE

// advanced parameters
#define CREATE_CHUNK_RADIUS 2  // 10
#define RENDER_CHUNK_RADIUS 1   // 10
#define RENDER_SIGN_RADIUS 1    // 4
#define DELETE_CHUNK_RADIUS 3   // 14
#define CHUNK_SIZE 16           // 32
#define COMMIT_INTERVAL 2       // 5

#endif
